const textModel = {
  en: {
    accept: "Accept",
    add: "Add",
    areYouSure: "Are you sure?",
    back: "Back",
    business: "business",
    calculatorError: "It doesn't make sense :D",
    calculatorErrorDivide: "Divide by 0 is forbidden.",
    calculatorName: "Calculator",
    changeAvatar: "Change Avatar",
    changeName: "Change name",
    changePIN: "Change PIN",
    chooseAvatar: "Avatar list",
    chooseLanguage: "Choose a language (English recommended)",
    close: "Close",
    closeAll: "Close all",
    closeProgram: "Close program",
    closeScreen1: "Thank you for using my app!",
    closeScreen2:
      " I wanted to showcase my skills in ReactJS, JavaScript, HTML, and CSS through this project. I had a lot of fun creating it. If you'd like, you can return to the start screen to create a new user or head to the login screen to explore the app again with the same user.",
    connectedToBackend: "Backend connected",
    country: "us",
    currentPIN: "Current PIN",
    dismiss: "Dismiss",
    dontShowAgain: "Don't show this again",
    enterPIN: "Enter new PIN",
    entertainment: "entertainment",
    fetchError: "Servers are overloaded. Try again later.",
    finalSummary: "Summary",
    finalSummaryDes: "Double-check everything looks correct before accepting",
    fontColor: "Font color",
    guestUser: "Guest user",
    home: "Home-page",
    iconsBig: "Big icons",
    iconsMedium: "Medium icons",
    iconsSmall: "Small icons",
    link: "Link",
    lng: "en-us",
    lngFetch: "en",
    loginButton: "Login",
    loginScreen: "Login Screen",
    mainColor: "Main color",
    maximize: "Maximize program window",
    minimize: "Minimize program window",
    name: "Name",
    news: "News",
    next: "Next",
    notConnectedToBackend: "Backend not connected",
    personalize: "Personalize",
    personalizeUser: "Personalize user",
    pin: "PIN (only digits)",
    pinForgetMsg: "I don't remember my PIN",
    pinPlaceholder: "PIN",
    refresh: "Refresh",
    remove: "Remove",
    repeatPIN: "Repeat PIN",
    samePIN: "PINs do not match. Please enter the same PIN in both inputs.",
    setDefault: "Set default theme",
    setUpPIN: "Ustaw PIN",
    showPin: "Show PIN",
    sport: "sports",
    startScreen: "Start screen",
    startScreenText1: "Welcome to my app!",
    startScreenText2:
      "You can log in using the guest user or create a new user.",
    startScreenText3: "Create user",
    startScreenText4: "Please provide name, last name, and PIN.",
    step1: "Click icon once to open an app.",
    step2:
      "This is menu start. You can check news here and also change user settings.",
    step3: "You can change the language here.",
    step4:
      "Click the right mouse button on the desktop to open a context menu. Have fun!",
    submit: "Submit",
    success: "Success.",
    technology: "technology",
    tetrisBack: "Back",
    tetrisControlKeys: "Control keys",
    tetrisGameOver: "Game Over",
    tetrisHelp: "Help",
    tetrisHighscore: "Highscore",
    tetrisHighscores: "Highscores",
    tetrisLevel: "Level",
    tetrisLines: "Lines",
    tetrisMoveLeft: "Move left",
    tetrisMoveRight: "Move right",
    tetrisNewGame: "New game",
    tetrisPause: "Pause",
    tetrisResume: "Resume",
    tetrisRotate: "Rotate",
    tetrisScore: "Score",
    tetrisSoftDrop: "Soft drop",
    tetrisYourScore: "Your score",
    toDoAppInputPlaceholder: "eg. buy eggs",
    uncheck: "Uncheck",
    undo: "Undo",
    userSetup: "Create user",
    userTag: "User tag",
    view: "View",
    wallpaper: "Wallpaper",
    webBrowserInfo:
      "Please note that this is a web browser simulation based on iframe, which may result in a significant number of errors. Additionally, most websites do not allow iframe at all. Please keep this in mind.",
    webBrowserInfoShort: "Iframe web browser",
    weather: "weather",
    weatherError1: "Allow for localization.",
    weatherError2: "Error fetching location.",
    weatherError3: "Error fetching weather.",
    wrongOldPIN: "Old PIN incorrect",
    yourAvatar: "Your avatar",
    yourPin: "Your pin",
  },
  pl: {
    accept: "Akceptuj",
    add: "Dodaj",
    areYouSure: "Jesteś pewny?",
    back: "Powrót",
    business: "biznes",
    calculatorError: "To nie ma sensu :D",
    calculatorErrorDivide: "Dzielenie przez 0 jest zabronione.",
    calculatorName: "Kalkulator",
    changeAvatar: "Zmień awatar",
    changeName: "Zmień imię",
    changePIN: "Zmień PIN",
    chooseAvatar: "Lista awatarów",
    chooseLanguage: "Wybierz język (zalecany angielski)",
    close: "Zamknij",
    closeAll: "Zamknij wszystko",
    closeProgram: "Zamknij program",
    closeScreen1: "Dziękuję za korzystanie z mojej aplikacji!",
    closeScreen2:
      "Poprzez ten projekt, chciałem zaprezentować swoje umiejętności w ReactJS, JavaScript, HTML i CSS. Dobrze się bawiłem, tworząc go. Jeśli chcesz, możesz wrócić do ekranu startowego, aby utworzyć nowego użytkownika lub przejść do ekranu logowania, aby ponownie korzystać z aplikacji jako ten sam użytkownik.",
    connectedToBackend: "Podłączono do backendu",
    country: "pl",
    currentPIN: "Obecny PIN",
    dismiss: "Odrzuć",
    dontShowAgain: "Nie pokazuj ponownie",
    enterPIN: "Wprowadź nowy PIN",
    entertainment: "rozrywka",
    fetchError: "Serwery są przeciążone. Spróbuj ponownie później.",
    finalSummary: "Podsumowanie",
    finalSummaryDes:
      "Sprawdź czy wszystko wygląda poprawnie przed zaakceptowaniem",
    fontColor: "Kolor czcionki",
    guestUser: "Gość",
    home: "Strona główna",
    iconsBig: "Duże ikony",
    iconsMedium: "Średnie ikony",
    iconsSmall: "Małe ikony",
    link: "Link",
    lng: "pl",
    lngFetch: "pl",
    loginButton: "Zaloguj",
    loginScreen: "Ekran logowania",
    mainColor: "Główny kolor",
    maximize: "Maksymalizuj okno programu",
    minimize: "Minimalizuj okno programu",
    name: "Imię",
    news: "Aktualności",
    next: "Dalej",
    notConnectedToBackend: "Brak połączenia z backendem",
    personalize: "Personalizuj",
    personalizeUser: "Personalizuj użytkownika",
    pin: "PIN (tylko cyfry)",
    pinForgetMsg: "Nie pamiętam mojego PIN-u",
    pinPlaceholder: "PIN",
    refresh: "Odśwież",
    remove: "Usuń",
    repeatPIN: "Powtórz PIN",
    samePIN: "PIN-y nie pasują. Proszę wprowadzić ten sam PIN w oba pola.",
    setDefault: "Ustaw domyślną tematykę",
    setUpPIN: "Ustaw PIN",
    showPin: "Pokaż PIN",
    sport: "sport",
    startScreen: "Ekran startowy",
    startScreenText1: "Witaj w mojej aplikacji!",
    startScreenText2:
      "Możesz zalogować się jako gość lub utworzyć nowego użytkownika.",
    startScreenText3: "Utwórz użytkownika",
    startScreenText4: "Podaj imię, nazwisko i PIN.",
    step1: "Kliknij ikonę raz, aby otworzyć aplikację.",
    step2:
      "To jest menu startowe. Tutaj możesz sprawdzić wiadomości i zmieniać ustawienia użytkownika.",
    step3: "Tutaj możesz zmienić język.",
    step4:
      "Kliknij prawym przyciskiem myszy na pulpicie, aby otworzyć menu kontekstowe. Baw się dobrze!",
    submit: "Wyślij",
    success: "Sukces.",
    technology: "technologia",
    tetrisBack: "Wstecz",
    tetrisControlKeys: "Klawisze kontrolne",
    tetrisGameOver: "Koniec gry",
    tetrisHelp: "Pomoc",
    tetrisHighscore: "Najwyższy wynik",
    tetrisHighscores: "Najwyższe wyniki",
    tetrisLevel: "Poziom",
    tetrisLines: "Linie",
    tetrisMoveLeft: "Przesuń w lewo",
    tetrisMoveRight: "Przesuń w prawo",
    tetrisNewGame: "Nowa gra",
    tetrisPause: "Pauza",
    tetrisResume: "Wznów",
    tetrisRotate: "Obróć",
    tetrisScore: "Wynik",
    tetrisSoftDrop: "Spadek miękki",
    tetrisYourScore: "Twój wynik",
    toDoAppInputPlaceholder: "np. kup jajka",
    uncheck: "Odznacz",
    undo: "Cofnij",
    userSetup: "Utwórz użytkownika",
    userTag: "Tag użytkownika",
    view: "Widok",
    wallpaper: "Tapeta",
    webBrowserInfo:
      "Proszę zauważyć, że to jest symulacja przeglądarki internetowej oparta na iframe, co może skutkować znaczną liczbą błędów. Ponadto, większość witryn w ogóle nie zezwala na wykorzystanie iframe. Proszę mieć to na uwadze.",
    webBrowserInfoShort: "Przeglądarka oparta na iframe",
    weather: "pogoda",
    weatherError1: "Zezwól na lokalizację.",
    weatherError2: "Błąd podczas pobierania lokalizacji.",
    weatherError3: "Błąd podczas pobierania pogody.",
    wrongOldPIN: "Nieprawidłowy stary PIN",
    yourAvatar: "Twój awatar",
    yourPin: "Twój PIN",
  },
};

export default textModel;
