const textModel = {
  en: {
    close: "Close",
    link: "Link",
    fetchError: "Servers are overloaded, please try again later!",
    sport: "sport",
    programming: "programming",
    politic: "politic",
    weather: "weather",
    accept: "Accept",
    areYouSure: "Are you sure?",
    dismiss: "Dismiss",
    lng: "en-us",
    lngFetch: "en",
    language: "language",
    startScreenText1:
      "Welcome to my app! Please use fullscreen mode for this app (press F11). This is starting form, you can choose all settings by yourself, or just use the default settings. Have fun!",
    startScreenText2:
      "This form doesn't have validation, so please be careful!",
    name: "name",
    surname: "surname",
    pin: "PIN",
    pinPlaceholder: "PIN number",
    pinForgetMsg: "I don't remember my PIN number",
    power: "Turn off computer",
    reset: "Restart computer",
    yourPin: "Your pin",
  },
  pl: {
    close: "Zamknij",
    link: "Link",
    fetchError: "Serwery są przeciążone, spróbuj ponownie później!",
    sport: "sport",
    programming: "programowanie",
    politic: "polityka",
    weather: "pogoda",
    accept: "Akceptuj",
    areYouSure: "Jesteś pewny?",
    dismiss: "Anuluj",
    lng: "pl",
    lngFetch: "pl",
    language: "język",
    startScreenText1:
      "Zapraszam do mojej aplikacji! Proszę używaj trybu pełnoekranowego do tej aplikacji (wciśnij F11). To jest formularz początkowy, możesz wybrać wszystkie ustawienia samodzielnie, lub po prostu użyć domyślnych ustawień. Baw się dobrze!",
    startScreenText2:
      "Ten formularz nie posiada walidacji, więc proszę bądź ostrożny!",
    name: "imię",
    surname: "nazwisko",
    pin: "PIN",
    pinPlaceholder: "Numer PIN",
    pinForgetMsg: "Nie pamiętam mojego numeru PIN",
    power: "wyłącz komputer",
    reset: "Restartuj komputer",
    yourPin: "Twój pin",
  },
};

export default textModel;
