const textModel = {
  en: {
    accept: "Accept",
    add: "Add",
    areYouSure: "Are you sure?",
    back: "Back",
    calculatorError: "It doesn't make sense :D",
    calculatorErrorDivide: "Divide by 0 is forbidden.",
    check: "Check!",
    chooseAvatar: "Avatar list",
    chooseLanguage: "Language",
    close: "Close",
    closeAll: "Close all",
    closeProgram: "Close program",
    closeScreen1: "Thank you for using my app!",
    closeScreen2:
      " I wanted to showcase my skills in ReactJS, JavaScript, HTML, and CSS through this project. I had a lot of fun creating it. If you'd like, you can return to the start screen to create a new user or head to the login screen to explore the app again with the same user.",
    defaultUser: "Default user",
    dismiss: "Dismiss",
    fetchError: "Servers are overloaded, please try again later!",
    finalSummary: "Summary",
    finalSummaryDes: "Double-check everything looks fine, before accepting",
    fontColor: "Font color",
    home: "Home-page",
    link: "Link",
    loginScreen: "Login Screen",
    lng: "en-us",
    lngFetch: "en",
    mainColor: "Main color",
    maximize: "Maximize program window",
    minimize: "Minimize program window",
    name: "Name (only letters)",
    news: "News",
    next: "Next",
    personalize: "Personalize",
    pin: "PIN (6 digits)",
    pinForgetMsg: "I don't remember my PIN number",
    pinPlaceholder: "PIN number",
    politic: "politic",
    programming: "programming",
    refresh: "Refresh",
    remove: "Remove",
    showPin: "Show PIN",
    sport: "sport",
    setDefault: "Set default theme",
    startScreen: "Start screen",
    startScreenText1: "Welcome to my app!",
    startScreenText2:
      "Here's the initial form of the application. You can either create your own user or use the default one. Have fun!",
    startScreenText3: "Create user",
    startScreenText4:
      "Please provide your name and surname, as well as your PIN.",
    submit: "Submit",
    surname: "Surname (only letters)",
    toDoAppInputPlaceholder: "eg. buy eggs",
    tetrisBack: "Back",
    tetrisHelp: "Help",
    tetrisControlKeys: "Control keys",
    tetrisMoveLeft: "Move left",
    tetrisMoveRight: "Move right",
    tetrisSoftDrop: "Soft drop",
    tetrisRotate: "Rotate",
    tetrisPause: "Pause",
    tetrisReset: "Reset",
    tetrisResume: "Resume",
    tetrisHighscores: "Highscores",
    tetrisHighscore: "Highscore",
    tetrisGameOver: "Game Over",
    tetrisLines: "Lines",
    tetrisLevel: "Level",
    tetrisNewGame: "New game",
    tetrisScore: "Score",
    tetrisYourScore: "Your score",

    uncheck: "Uncheck",
    userSetup: "Create user",
    view: "View",
    wallpaper: "Wallpaper",
    webBrowserInfo:
      "Please note that this is a web browser simulation based on iframe, which may result in a significant number of errors. Additionally, most websites do not allow iframe at all. Please keep this in mind.",
    webBrowserInfoShort: "Iframe web browser",
    weather: "weather",
    yourAvatar: "Your avatar",
    yourPin: "Your pin",
  },
  pl: {
    accept: "Akceptuj",
    add: "Dodaj",
    areYouSure: "Jesteś pewny?",
    back: "Wstecz",
    calculatorError: "To nie ma sensu.",
    calculatorErrorDivide: "Dzielenie przez 0 jest zabronione.",
    check: "Zaznaczone",
    chooseAvatar: "Lista avatarów",
    chooseLanguage: "Język",
    close: "Zamknij",
    closeAll: "Zamknij wszystko",
    closeProgram: "Zamknij program",
    closeScreen1: "Dziękuję za korzystanie z mojej aplikacji!",
    closeScreen2:
      " Chciałem tutaj zaprezentować moje umiejętności związane z ReactJS, JavaScript, HTML i CSS. Tworząc tę aplikację, świetnie się bawiłem. Jeśli chcesz, możesz przejść ponownie do ekranu startowego, aby stworzyć nowego użytkownika lub przejść do ekranu logowania, aby ponownie sprawdzić aplikację z tym samym użytkownikiem.",
    defaultUser: "Użytkownik domyślny",
    dismiss: "Anuluj",
    fetchError: "Serwery są przeciążone, spróbuj ponownie później!",
    finalSummary: "Podsumowanie",
    finalSummaryDes: "Sprawdź czy wszystko pasuje, przed akceptacją",
    fontColor: "Color czcionki",
    home: "Strona startowa",
    link: "Link",
    loginScreen: "Ekran logowanie",
    lng: "pl",
    lngFetch: "pl",
    mainColor: "Kolor główny",
    maximize: "Zmaksymalizuj okno programu",
    minimize: "Zminimalizuj okno programu",
    name: "Imię (tylko litery)",
    news: "Nowości",
    next: "Dalej",
    personalize: "Personalizuj",
    pin: "PIN (6 cyfr)",
    pinForgetMsg: "Nie pamiętam mojego numeru PIN",
    pinPlaceholder: "Numer PIN",
    politic: "polityka",
    programming: "programowanie",
    refresh: "Odśwież",
    remove: "Usuń",
    submit: "Potwierdź",
    reset: "Uruchom ponownie",
    setDefault: "Ustaw motyw domyślny",
    showPin: "Pokaż PIN",
    sport: "sport",
    startScreen: "Ekran startowy",
    startScreenText1: "Witam w mojej aplikacji!",
    startScreenText2:
      "Oto formularz początkowy aplikacji. Masz możliwość stworzenia swojego własnego użytkownika lub skorzystania z domyślnego. Życzę przyjemnej zabawy!",
    startScreenText3: "Stwórz użytkownika",
    startScreenText4: "Proszę podać imię, nazwisko oraz PIN.",
    surname: "Nazwisko (tylko litery)",
    toDoAppInputPlaceholder: "np. kup jajka",
    tetrisBack: "Powrót",
    tetrisHelp: "Pomoc",
    tetrisControlKeys: "Klawisze sterujące",
    tetrisMoveLeft: "Przesuń w lewo",
    tetrisMoveRight: "Przesuń w prawo",
    tetrisSoftDrop: "Miękkie opuszczenie",
    tetrisRotate: "Obróć",
    tetrisPause: "Pauza",
    tetrisReset: "Resetuj",
    tetrisResume: "Wznów",
    tetrisHighscores: "Wyniki",
    tetrisHighscore: "Najlepszy wynik",
    tetrisGameOver: "Koniec gry",
    tetrisLines: "Linie",
    tetrisLevel: "Poziom",
    tetrisNewGame: "Nowa gra",
    tetrisScore: "Wynik",
    tetrisYourScore: "Twój wynik",
    uncheck: "Odznaczone",
    userSetup: "Stwórz użytkownika",
    view: "Widok",
    wallpaper: "Tapeta",
    weather: "pogoda",
    webBrowserInfo:
      "Proszę zwrócić uwagę, że ta symulacja przeglądarki internetowej oparta jest na elementach iframe, co może prowadzić do dużej liczby błędów. Dodatkowo większość stron internetowych w ogóle nie pozwalają na wykorzystanie iframe. Proszę o zachowanie tego w pamięci.",
    webBrowserInfoShort: "Iframe przeglądarka internetowa",
    yourAvatar: "Twój avatar",
    yourPin: "Twój PIN",
  },
};

export default textModel;
